[snowflake]
account = "VKOZIAJ-KC24613"
user = "ABHAY2004"
password = "Abhay@7505991639"
warehouse = "DS_WH"
database = "DS_GROUP_DB"
schema = "OUTLET_SCHEMA"
role = "SYSADMIN"

[app]
admin_email = "dubeyabhay430@gmail.com"
